/**
 * src/graphs/codeGraph.ts
 * LangGraph code review agent: Syntax → Security → Complexity → AI Review → Report
 */
import { StateGraph, START, END, MemorySaver, Annotation } from "@langchain/langgraph";
import { HumanMessage, AIMessage } from "@langchain/core/messages";
import { getLLM, CODE_REVIEW_SYSTEM } from "@/config/settings";
import { analyzeSyntax, checkSecurity, analyzeComplexity } from "@/tools/codeTools";

// ── State ────────────────────────────────────────────────────────────────────

const CodeStateAnnotation = Annotation.Root({
  code: Annotation<string>,
  language: Annotation<string>,
  syntaxReport: Annotation<string>,
  securityReport: Annotation<string>,
  complexityReport: Annotation<string>,
  llmReview: Annotation<string>,
  finalReport: Annotation<string>,
  severity: Annotation<"clean" | "minor" | "moderate" | "critical">,
  messages: Annotation<(HumanMessage | AIMessage)[]>({
    reducer: (a, b) => [...a, ...b],
    default: () => [],
  }),
});

type CodeState = typeof CodeStateAnnotation.State;

// ── Nodes ────────────────────────────────────────────────────────────────────

async function syntaxNode(state: CodeState): Promise<Partial<CodeState>> {
  const result = await analyzeSyntax.invoke({ code: state.code, language: state.language });
  return { syntaxReport: result, messages: [new AIMessage("🔬 Syntax analysis complete.")] };
}

async function securityNode(state: CodeState): Promise<Partial<CodeState>> {
  const result = await checkSecurity.invoke({ code: state.code });
  return { securityReport: result, messages: [new AIMessage("🔒 Security scan complete.")] };
}

async function complexityNode(state: CodeState): Promise<Partial<CodeState>> {
  const result = await analyzeComplexity.invoke({ code: state.code });
  return { complexityReport: result, messages: [new AIMessage("📊 Complexity analysis complete.")] };
}

async function llmReviewerNode(state: CodeState): Promise<Partial<CodeState>> {
  const llm = getLLM(0.3);
  const response = await llm.invoke([
    { role: "system", content: CODE_REVIEW_SYSTEM },
    new HumanMessage(
      `Review this ${state.language} code:\n\`\`\`${state.language}\n${state.code}\n\`\`\`\n\n` +
      `Static Analysis:\nSyntax: ${state.syntaxReport}\nSecurity: ${state.securityReport}\nComplexity: ${state.complexityReport}\n\n` +
      "Provide a code review with:\n" +
      "1. **Overall Quality** (rate 1-10)\n" +
      "2. **Issues Found** (🔴 Critical / 🟡 Medium / 🟢 Minor)\n" +
      "3. **Best Practice Violations**\n" +
      "4. **Performance Considerations**\n" +
      "5. **Specific Improvement Suggestions** (with code examples)\n" +
      "6. **Positive Aspects**"
    ),
  ]);
  const content = String(response.content);
  let severity: CodeState["severity"] = "clean";
  if (content.includes("🔴") || content.toLowerCase().includes("critical")) severity = "critical";
  else if (content.includes("🟡") || content.toLowerCase().includes("medium")) severity = "moderate";
  else if (content.includes("🟢") || content.toLowerCase().includes("minor")) severity = "minor";

  return { llmReview: content, severity, messages: [new AIMessage("🤖 AI review complete.")] };
}

async function reportFormatterNode(state: CodeState): Promise<Partial<CodeState>> {
  const severityEmoji = { clean: "✅", minor: "🟢", moderate: "🟡", critical: "🔴" }[state.severity];
  const report = `# 🔍 Code Review Report

**Language:** ${state.language} | **Severity:** ${severityEmoji} ${state.severity.toUpperCase()}

---

## 📋 Static Analysis

### Syntax Check
${state.syntaxReport}

### 🔒 Security Scan
${state.securityReport}

### 📊 Complexity Analysis
${state.complexityReport}

---

## 🤖 AI Code Review

${state.llmReview}

---
*Generated by AI Code Review Agent powered by Claude + LangGraph (TypeScript)*
`;
  return { finalReport: report, messages: [new AIMessage("✅ Report ready!")] };
}

// ── Graph Builder ────────────────────────────────────────────────────────────

let _codeGraph: ReturnType<typeof buildCodeGraph> | null = null;

export function buildCodeGraph() {
  const builder = new StateGraph(CodeStateAnnotation);

  builder.addNode("syntax", syntaxNode);
  builder.addNode("security", securityNode);
  builder.addNode("complexity", complexityNode);
  builder.addNode("llmReviewer", llmReviewerNode);
  builder.addNode("reportFormatter", reportFormatterNode);

  builder.addEdge(START, "syntax");
  builder.addEdge("syntax", "security");
  builder.addEdge("security", "complexity");
  builder.addEdge("complexity", "llmReviewer");
  builder.addEdge("llmReviewer", "reportFormatter");
  builder.addEdge("reportFormatter", END);

  const memory = new MemorySaver();
  return builder.compile({ checkpointer: memory });
}

export async function reviewCode(
  code: string,
  language = "typescript",
  threadId = "review-1"
): Promise<string> {
  if (!_codeGraph) _codeGraph = buildCodeGraph();
  const config = { configurable: { thread_id: threadId } };
  const result = await _codeGraph.invoke(
    {
      code,
      language,
      syntaxReport: "",
      securityReport: "",
      complexityReport: "",
      llmReview: "",
      finalReport: "",
      severity: "clean",
      messages: [new HumanMessage(`Review this ${language} code`)],
    },
    config
  );
  return result.finalReport;
}
